openapi: 3.0.3
info:
  title: Your API Title
  description: Description of your API
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Local development server
paths:
  /auth/verified:
    get:
      tags:
        - auth
      summary: Verify Authentication
      description: Verifies the authentication status of a user
      responses:
        "200":
          description: Authentication verified successfully
        "401":
          description: Unauthorized access
    # Add other HTTP methods and routes here

  /auth/register:
    post:
      tags:
        - auth
      summary: User Registration
      description: Registers a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: User's username
                password:
                  type: string
                  description: User's password
      responses:
        "200":
          description: User registered successfully
        "400":
          description: Invalid request payload

  /movie/detail/{movieID}:
    get:
      tags:
        - movie
      summary: Get Movie Details
      description: Retrieves details of a specific movie
      parameters:
        - in: path
          name: movieID
          required: true
          schema:
            type: integer
            format: int64
          description: ID of the movie E.g 502356
      responses:
        "200":
          description: Movie details retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MovieDetail"
        "404":
          description: Access Denied or Movie ID Not Found
        "500":
          description: Internal Server Error

  /movie/recommendations/{movieID}:
    get:
      tags:
        - movie
      summary: Get Movie Recommendations
      description: Retrieves a list of recommended movies based on a given movie
      parameters:
        - in: path
          name: movieID
          required: true
          schema:
            type: integer
            format: int64
          description: ID of the movie E.g 502356
      responses:
        "200":
          description: Movie recommendations retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MovieRecommendations"
        "404":
          description: Access Denied or Movie ID Not Found
        "500":
          description: Internal Server Error

  /movie/trailer/{movieID}:
    get:
      tags:
        - movie
      summary: Get Movie Trailer
      description: Retrieves the trailer of a specific movie
      parameters:
        - in: path
          name: movieID
          required: true
          schema:
            type: string
          description: ID of the movie E.g 502356
      responses:
        "200":
          description: Movie trailer retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MovieTrailer"
        "404":
          description: Access Denied or Movie ID Not Found
        "500":
          description: Internal Server Error

  /movie/tvDetail/{showID}:
    get:
      tags:
        - tv show
      summary: Get TV show details
      description: Retrieve the Details of a specific TV show
      parameters:
        - in: path
          name: showID
          required: true
          schema:
            type: string
          description: ID of the tv show E.g 94605
      responses:
        "200":
          description: TV Show Data retrieved successfully
          content:
            application/json:
        "404":
          description: Access Denied or TV ID Not Found
        "500":
          description: Internal Server Error
  /movie/showTrailer/{showID}:
    get:
      tags:
        - tv show
      summary: Get TV show details
      description: Retrieve the Details of a specific TV show
      parameters:
        - in: path
          name: showID
          required: true
          schema:
            type: string
          description: ID of the tv show E.g 94605
      responses:
        "200":
          description: TV Show Data retrieved successfully
          content:
            application/json:
        "404":
          description: Access Denied or TV ID Not Found
        "500":
          description: Internal Server Error
  /movie/tvRecommendations/{showID}:
    get:
      tags:
        - tv show
      summary: Get TV show details
      description: Retrieve the Details of a specific TV show
      parameters:
        - in: path
          name: showID
          required: true
          schema:
            type: string
          description: ID of the tv show E.g 94605
      responses:
        "200":
          description: TV Show Data retrieved successfully
          content:
            application/json:
        "404":
          description: Access Denied or TV ID Not Found
        "500":
          description: Internal Server Error

  /movie/discovery/{page}:
    get:
      tags:
        - discovery
      summary: Get TV show details
      description: Retrieve the Details of a specific TV show
      parameters:
        - in: path
          name: showID
          required: true
          schema:
            type: string
          description: ID of the tv show E.g 94605
      responses:
        "200":
          description: TV Show Data retrieved successfully
          content:
            application/json:
        "404":
          description: Access Denied or TV ID Not Found
        "500":
          description: Internal Server Error
  /movie/showDiscovery/{page}:
    get:
      tags:
        - discovery
      summary: Get TV show details
      description: Retrieve the Details of a specific TV show
      parameters:
        - in: path
          name: showID
          required: true
          schema:
            type: string
          description: ID of the tv show E.g 94605
      responses:
        "200":
          description: TV Show Data retrieved successfully
          content:
            application/json:
        "404":
          description: Access Denied or TV ID Not Found
        "500":
          description: Internal Server Error

# Add other paths and endpoints here

components:
  schemas:
    Genre:
      type: object
      properties:
        id:
          type: integer
          description: ID of the genre
        name:
          type: string
          description: Name of the genre

    ProductionCompany:
      type: object
      properties:
        id:
          type: integer
          description: ID of the production company
        logo_path:
          type: string
          description: Path to the production company's logo
        name:
          type: string
          description: Name of the production company
        origin_country:
          type: string
          description: Origin country of the production company

    ProductionCountry:
      type: object
      properties:
        iso_3166_1:
          type: string
          description: ISO 3166-1 code of the production country
        name:
          type: string
          description: Name of the production country

    SpokenLanguage:
      type: object
      properties:
        english_name:
          type: string
          description: English name of the spoken language
        iso_639_1:
          type: string
          description: ISO 639-1 code of the spoken language
        name:
          type: string
          description: Name of the spoken language

    MovieDetail:
      type: object
      properties:
        adult:
          type: boolean
          description: Indicates if the movie is suitable for adults
          example: false
        backdrop_path:
          type: string
          description: Path to the backdrop image of the movie
          example: /9n2tJBplPbgR2ca05hS5CKXwP2c.jpg
        belongs_to_collection:
          type: object
          nullable: true
          description: Collection details the movie belongs to
          example: null
        budget:
          type: integer
          description: Budget of the movie
          example: 100000000
        genres:
          type: array
          items:
            $ref: "#/components/schemas/Genre"
          description: List of genres of the movie
          example:
            - id: 16
              name: Animation
            - id: 12
              name: Adventure
            - id: 10751
              name: Family
            - id: 14
              name: Fantasy
            - id: 35
              name: Comedy
        homepage:
          type: string
          description: Official homepage of the movie
          example: https://www.thesupermariobros.movie
        id:
          type: integer
          description: ID of the movie
          example: 502356
        imdb_id:
          type: string
          description: IMDb ID of the movie
          example: tt6718170
        original_language:
          type: string
          description: Original language of the movie
          example: en
        original_title:
          type: string
          description: Original title of the movie
          example: The Super Mario Bros. Movie
        overview:
          type: string
          description: Overview of the movie
          example: While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.
        popularity:
          type: number
          description: Popularity score of the movie
          example: 2915.871
        poster_path:
          type: string
          description: Path to the poster image of the movie
          example: /qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg
        production_companies:
          type: array
          items:
            $ref: "#/components/schemas/ProductionCompany"
          description: List of production companies involved in the movie
        production_countries:
          type: array
          items:
            $ref: "#/components/schemas/ProductionCountry"
          description: List of production countries of the movie
          example:
            - iso_3166_1: JP
              name: Japan
            - iso_3166_1: US
              name: United States of America
        release_date:
          type: string
          format: date
          description: Release date of the movie
          example: 2023-04-05
        revenue:
          type: integer
          description: Revenue generated by the movie
          example: 1162684440
        runtime:
          type: integer
          description: Runtime of the movie in minutes
          example: 92
        spoken_languages:
          type: array
          items:
            $ref: "#/components/schemas/SpokenLanguage"
          description: List of spoken languages in the movie
          example:
            - english_name: English
              iso_639_1: en
              name: English
        status:
          type: string
          example: Released
        tagline:
          type: string
        title:
          type: string
          description: The Title of the Movie
          example: The Super Mario Bros. Movie
        vote_average:
          type: number
          example: 7.447
        vote_count:
          type: integer
          example: 1987

    MovieRecommendations:
      type: object
      properties:
        page:
          type: integer
          example: 1
        results:
          type: array
          items:
            $ref: "#/components/schemas/MovieDetail"
          description: List of movie's recommendations
          example:
            - adult: false
              backdrop_path: /aAgGrfBwna1nO4M2USxwFgK5O0t.jpg
              id: 713704
              title: Evil Dead Rise
              original_language: en
              original_title: Evil Dead Rise
              overview: Three siblings find an ancient vinyl that gives birth to bloodthirsty demons that run amok in a Los Angeles apartment building and thrusts them into a primal battle for survival as they face the most nightmarish version of family imaginable.
              poster_path: /5ik4ATKmNtmJU6AYD0bLm56BCVM.jpg
              media_type: movie
              genre_ids:
                - id: 27
                - id: 53
              popularity: 4254.799
              release_date: "2023-04-12"
              vote_average: 7.201
              vote_count: 755

    TrailerVideo:
      type: object
      properties:
        iso_639_1:
          type: string
          description: ISO 639-1 code of the video
          example: en
        iso_3166_1:
          type: string
          description: ISO 3166-1 code of the video
          example: US
        name:
          type: string
          description: Name of the video
          example: TV Spot 66
        key:
          type: string
          description: Key of the video
          example: LTFGH0rJ-EY
        site:
          type: string
          description: Site where the video is hosted
          example: YouTube
        size:
          type: integer
          description: Size of the video
          example: 1080
        type:
          type: string
          description: Type of the video
          example: Teaser
        official:
          type: boolean
          description: Indicates if the video is official
          example: true
        published_at:
          type: string
          format: date-time
          description: Publish date of the video
          example: "2023-04-10T19:29:54.000Z"
        id:
          type: string
          description: ID of the video
          example: 6439b5ee2938350479a99eb2

    MovieTrailer:
      type: object
      properties:
        page:
          type: integer
          example: 1
        items:
          type: array
          items:
            $ref: "#/components/schemas/TrailerVideo"
          description: List of movie trailer's youtube id
          example:
            - iso_639_1: en
              iso_3166_1: US
              name: TV Spot 66
              key: LTFGH0rJ-EY
              site: YouTube
              size: 1080
              type: Teaser
              official: true
              published_at: "2023-04-10T19:29:54.000Z"
              id: 6439b5ee2938350479a99eb2
